// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuoteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteOrderRequest) Reset() {
	*x = QuoteOrderRequest{}
	mi := &file_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteOrderRequest) ProtoMessage() {}

func (x *QuoteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteOrderRequest.ProtoReflect.Descriptor instead.
func (*QuoteOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *QuoteOrderRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *QuoteOrderRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// OrderQuote is the price breakdown returned by the
// calculate-order-price serverless function.
type OrderQuote struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName    string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity       int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice      float64                `protobuf:"fixed64,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Subtotal       float64                `protobuf:"fixed64,5,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	DiscountRate   float64                `protobuf:"fixed64,6,opt,name=discount_rate,json=discountRate,proto3" json:"discount_rate,omitempty"`
	Discount       float64                `protobuf:"fixed64,7,opt,name=discount,proto3" json:"discount,omitempty"`
	DeliveryFee    float64                `protobuf:"fixed64,8,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	Total          float64                `protobuf:"fixed64,9,opt,name=total,proto3" json:"total,omitempty"`
	PricingRules   []string               `protobuf:"bytes,10,rep,name=pricing_rules,json=pricingRules,proto3" json:"pricing_rules,omitempty"`
	PricingVersion string                 `protobuf:"bytes,11,opt,name=pricing_version,json=pricingVersion,proto3" json:"pricing_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderQuote) Reset() {
	*x = OrderQuote{}
	mi := &file_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderQuote) ProtoMessage() {}

func (x *OrderQuote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderQuote.ProtoReflect.Descriptor instead.
func (*OrderQuote) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderQuote) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderQuote) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderQuote) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderQuote) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *OrderQuote) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *OrderQuote) GetDiscountRate() float64 {
	if x != nil {
		return x.DiscountRate
	}
	return 0
}

func (x *OrderQuote) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *OrderQuote) GetDeliveryFee() float64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *OrderQuote) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderQuote) GetPricingRules() []string {
	if x != nil {
		return x.PricingRules
	}
	return nil
}

func (x *OrderQuote) GetPricingVersion() string {
	if x != nil {
		return x.PricingVersion
	}
	return ""
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOrderRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateOrderRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Order struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	OrderId    string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ProductId  string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity   int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TotalPrice float64                `protobuf:"fixed64,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Status     string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// payment_id is the reference returned by the Payment
	// Service for the charge that paid for this order, so a
	// customer can see the payment their order was settled by.
	PaymentId string `protobuf:"bytes,7,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// product_name is carried on the order so order history can
	// be shown without calling the Product Service again for
	// every line.
	ProductName string `protobuf:"bytes,8,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	// The price breakdown from the calculate-order-price
	// serverless function. total_price is subtotal - discount +
	// delivery_fee, and is the amount the Payment Service charged.
	Subtotal      float64  `protobuf:"fixed64,9,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Discount      float64  `protobuf:"fixed64,10,opt,name=discount,proto3" json:"discount,omitempty"`
	DeliveryFee   float64  `protobuf:"fixed64,11,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	PricingRules  []string `protobuf:"bytes,12,rep,name=pricing_rules,json=pricingRules,proto3" json:"pricing_rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{3}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Order) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Order) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Order) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Order) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *Order) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *Order) GetDeliveryFee() float64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *Order) GetPricingRules() []string {
	if x != nil {
		return x.PricingRules
	}
	return nil
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_proto_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrdersRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

var File_proto_order_proto protoreflect.FileDescriptor

const file_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x11proto/order.proto\x12\x05order\"N\n" +
	"\x11QuoteOrderRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\xed\x02\n" +
	"\n" +
	"OrderQuote\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x01R\tunitPrice\x12\x1a\n" +
	"\bsubtotal\x18\x05 \x01(\x01R\bsubtotal\x12#\n" +
	"\rdiscount_rate\x18\x06 \x01(\x01R\fdiscountRate\x12\x1a\n" +
	"\bdiscount\x18\a \x01(\x01R\bdiscount\x12!\n" +
	"\fdelivery_fee\x18\b \x01(\x01R\vdeliveryFee\x12\x14\n" +
	"\x05total\x18\t \x01(\x01R\x05total\x12#\n" +
	"\rpricing_rules\x18\n" +
	" \x03(\tR\fpricingRules\x12'\n" +
	"\x0fpricing_version\x18\v \x01(\tR\x0epricingVersion\"p\n" +
	"\x12CreateOrderRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\xf9\x02\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\x01R\n" +
	"totalPrice\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"payment_id\x18\a \x01(\tR\tpaymentId\x12!\n" +
	"\fproduct_name\x18\b \x01(\tR\vproductName\x12\x1a\n" +
	"\bsubtotal\x18\t \x01(\x01R\bsubtotal\x12\x1a\n" +
	"\bdiscount\x18\n" +
	" \x01(\x01R\bdiscount\x12!\n" +
	"\fdelivery_fee\x18\v \x01(\x01R\vdeliveryFee\x12#\n" +
	"\rpricing_rules\x18\f \x03(\tR\fpricingRules\"4\n" +
	"\x11ListOrdersRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId2\xc3\x01\n" +
	"\fOrderService\x126\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\f.order.Order\x12@\n" +
	"\x14ListOrdersByCustomer\x12\x18.order.ListOrdersRequest\x1a\f.order.Order0\x01\x129\n" +
	"\n" +
	"QuoteOrder\x12\x18.order.QuoteOrderRequest\x1a\x11.order.OrderQuoteB\x1fZ\x1decommerce-microservices/protob\x06proto3"

var (
	file_proto_order_proto_rawDescOnce sync.Once
	file_proto_order_proto_rawDescData []byte
)

func file_proto_order_proto_rawDescGZIP() []byte {
	file_proto_order_proto_rawDescOnce.Do(func() {
		file_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)))
	})
	return file_proto_order_proto_rawDescData
}

var file_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_order_proto_goTypes = []any{
	(*QuoteOrderRequest)(nil),  // 0: order.QuoteOrderRequest
	(*OrderQuote)(nil),         // 1: order.OrderQuote
	(*CreateOrderRequest)(nil), // 2: order.CreateOrderRequest
	(*Order)(nil),              // 3: order.Order
	(*ListOrdersRequest)(nil),  // 4: order.ListOrdersRequest
}
var file_proto_order_proto_depIdxs = []int32{
	2, // 0: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	4, // 1: order.OrderService.ListOrdersByCustomer:input_type -> order.ListOrdersRequest
	0, // 2: order.OrderService.QuoteOrder:input_type -> order.QuoteOrderRequest
	3, // 3: order.OrderService.CreateOrder:output_type -> order.Order
	3, // 4: order.OrderService.ListOrdersByCustomer:output_type -> order.Order
	1, // 5: order.OrderService.QuoteOrder:output_type -> order.OrderQuote
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_order_proto_init() }
func file_proto_order_proto_init() {
	if File_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_proto_goTypes,
		DependencyIndexes: file_proto_order_proto_depIdxs,
		MessageInfos:      file_proto_order_proto_msgTypes,
	}.Build()
	File_proto_order_proto = out.File
	file_proto_order_proto_goTypes = nil
	file_proto_order_proto_depIdxs = nil
}
